### ISSUE TITLE
Handler 'create_fn' failed with an exception.

### ISSUE THREAD

**Issue by amartingarcia** [devopstales/trivy-operator#26]
**Describe the bug**
Hello,
I deployed trivy-operator on a Kubernetes cluster. After running scans it shows the following error.

```python
[2022-07-19 07:41:52,874] kopf.objects         [ERROR   ] [trivy-operator/trivy-operator-main-config] Handler 'create_fn' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/execution.py", line 279, in execute_handler_once
    result = await invoke_handler(
  File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/execution.py", line 374, in invoke_handler
    result = await invocation.invoke(
  File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/invocation.py", line 116, in invoke
    result = await fn(**kwargs)  # type: ignore
  File "/trivy-operator.py", line 518, in create_fn
    "links": item["References"],
KeyError: 'References'
```

**Configuration file**
```yaml
apiVersion: v1
items:
- apiVersion: trivy-operator.devopstales.io/v1
  kind: NamespaceScanner
  metadata:
    annotations:
      helm.sh/hook: post-install,post-upgrade
      kopf.zalando.org/create_fn: '{"started":"2022-07-19T07:34:05.809742","delayed":"2022-07-19T07:42:52.875942","purpose":"create","retries":1,"success":false,"failure":false,"message":"''References''"}'
      kopf.zalando.org/touch-dummy: 2022-07-19T07:42:52.903900
    creationTimestamp: "2022-07-19T07:34:03Z"
    generation: 3
    name: trivy-operator-main-config
    namespace: trivy-operator
    resourceVersion: "63425144"
    uid: 2f7ec00c-03f3-4760-a3dc-0af3618d7920
  spec:
    clusterWide: false
    crontab: '*/5 * * * *'
    namespace_selector: trivy-scan
    registry:
    - name: ****
      password: ****
      user: ****
  status:
    kopf:
      dummy: 2022-07-19T07:42:52.903900
      progress:
        create_fn:
          delayed: 2022-07-19T07:42:52.875942
          failure: false
          message: '''References'''
          purpose: create
          retries: 1
          started: 2022-07-19T07:34:05.809742
          success: false
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Helm Values file**
```yaml
image:
  repository: devopstales/trivy-operator
  pullPolicy: Always
  tag: "2.4"

# Log level
log_level: "DEBUG"
# INFO, HIGH, DEBUG

imagePullSecrets: []
podSecurityContext:
  fsGroup: 0

serviceAccount:
  create: true
  annotations: {}
  name: "trivy-operator"

# enable tu deploy redis as cache
cache:
  enabled: false

monitoring:
  port: "9115"

# deploy service monitor
serviceMonitor:
  enabled: true
  labels:
    release: prometheus
  # Scrape interval. If not set, the Prometheus default scrape interval is used.
  #
  interval: 60s
  scrapeTimeout: 30s
  ## RelabelConfigs to apply to samples before scraping
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
  ##
  relabelings:
  - action: replace
    regex: (.*)
    replacement: develop
    sourceLabels:
    - __address__
    targetLabel: account
  - action: replace
    regex: (.*)
    replacement: aws
    sourceLabels:
    - __address__
    targetLabel: provider
  - action: replace
    sourceLabels:
    - __metrics_path__
    targetLabel: metrics_path
  - sourceLabels: [job]
    regex: (.*)
    action: replace
    targetLabel: namespace
    replacement: "monitoring"
  metricRelabelings:
  - action: replace
    regex: (.*)
    sourceLabels:
    - severity
    targetLabel: severity_vulnerability
  - action: labeldrop
    regex: severity

persistence:
  enabled: true
  accessMode: "ReadWriteOnce"
  size: "1Gi"
  annotations: {}
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: "gp3-ephemeral"

# content foc ns-scan CRD
namespaceScanner:
  crontab: "*/5 * * * *"
  namespaceSelector: "trivy-scan"
  clusterWide: false
  policyreport: false

# enable adission controller
admissionController:
  enabled: false

# authentication informatin for trivy to use wen scan image
registryAuth:
  enabled: true
  registry:
  - name: ****
    user: ****
    password: ****

# github authentiation token for trivy database download
githubToken:
  enabled: false
  token: ""

## Define which Nodes the Pods are scheduled on.
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector:
  project: work

## Tolerations for use with node taints
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations:
  - effect: NoSchedule
    key: project
    operator: Equal
    value: work
## Assign custom affinity rules to the trivy operator
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
##
affinity: {}
# nodeAffinity:
#   requiredDuringSchedulingIgnoredDuringExecution:
#     nodeSelectorTerms:
#     - matchExpressions:
#       - key: kubernetes.io/e2e-az-name
#         operator: In
#         values:
#         - e2e-az1
#         - e2e-az2

```

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 2.4
- Installation type (Helm, Kubernetes, OperatorFramework): Helm
- Kubernetes version (use `kubectl version`):  v1.21.10

Thanks!

**Comment by devopstales** [comment]
@amartingarcia Your pull request wont triggered the update of the hem chart. I triggered manually and with that the trivy-operator version 2.4.1 bug-fix version is out. Test wit that please.
